Added Go backend service basic structure
FlamingoTP/cardz pull request #1
Opened 2024-11-23 20:50 UTC by ivantomic77

Added Go backend basic structure with one /api/health endpoint.

2024-11-24 14:00 UTC, LukaPlejic requested changes

2024-11-24 14:00 UTC, LukaPlejic commented on backend/internal/handlers.go
Rename this file to `health.go`
and change it's path to `backend\internal\handlers\health.go`

2024-11-24 14:00 UTC, LukaPlejic commented on backend/cmd/api/api.go
Move this file to `backend\internal\api`

2024-11-24 14:00 UTC, LukaPlejic commented on backend/cmd/api/main.go
> +}
This can be extracted to a specific `helpers` package for further reusability

2024-11-24 14:00 UTC, LukaPlejic commented on backend/cmd/api/api.go
> +}
Use Uppercase for Struct names
e.g. `Application`, `Config`

2024-11-24 14:00 UTC, LukaPlejic commented on README.adoc
> +== Changelog
Shouldn't changelog be it's own .md file?

2024-11-25 16:02 UTC, ivantomic77 commented on README.adoc
> +== Changelog
Yes, it will be. I left a slot for the link to the CHANGELOG file.

2024-11-25 16:05 UTC, ivantomic77 commented
@LukaPlejic Please check the changes I made and close threads if resolved.

2024-11-27 19:38 UTC, LukaPlejic approved these changes

2024-11-27 20:57 UTC, merged